# Generated by Django 3.2.1 on 2021-06-14 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mypage', '0004_auto_20210614_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsforlaboratory',
            name='send_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_for_laboratory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationsforuser',
            name='send_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_for_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationsforuser',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='notification_for_user', to='accounts.user'),
            preserve_default=False,
        ),
    ]
