# Generated by Django 3.2.1 on 2021-06-14 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210521_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_laboratory',
        ),
    ]
