# Generated by Django 3.2.1 on 2021-06-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_image'),
        ('accounts', '0007_remove_user_favorite_laboratory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_laboratory',
            field=models.ManyToManyField(blank=True, related_name='person_favorite_laboratory_info', to='search.LaboratoryInfo', verbose_name='お気に入り研究室'),
        ),
    ]
