# Generated by Django 3.2.1 on 2021-06-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_favorite_laboratory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status_position',
            field=models.CharField(choices=[('学部1年生', 'B1'), ('学部2年生', 'B2'), ('学部3年生', 'B3'), ('学部4年生', 'B4'), ('学部5年生', 'B5'), ('学部6年生', 'B6'), ('修士1年生', 'M1'), ('修士2年生', 'M2'), ('博士1年生', 'D1'), ('博士2年生', 'D2'), ('博士3年生', 'D3'), ('研究室関係者(教員)', 'PhD'), ('その他', 'その他')], max_length=64, verbose_name='身分'),
        ),
    ]
