# Generated by Django 3.2.1 on 2021-06-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryinfo',
            name='Employment_rate',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='laboratoryinfo',
            name='degree_of_difficulty',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='laboratoryinfo',
            name='environment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='laboratoryinfo',
            name='students_rate',
            field=models.TextField(blank=True),
        ),
    ]
